services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Undkonsorten\Powermailpdf\EventListener\CreateActionBeforeRenderView:
    tags:
      - name: event.listener
        identifier: 'CreateActionBeforeRenderView'
